config/routes.rb
Rails.application.routes.draw do
  root 'reviews#index'
  get 'reviews/search'
  resources :reviews do
    resources :comments, only: :create
  end
  
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '〜19才' },
    { id: 3, name: '20〜24才' },
    { id: 4, name: '25〜29才' },
    { id: 5, name: '30〜34才' },
    { id: 6, name: '35〜39才' },
    { id: 7, name: '40〜44才' },
    { id: 8, name: '45〜49才' },
    { id: 9, name: '50〜54才' },
    { id: 10, name: '55〜59才' },
    { id: 11, name: '60才〜' }
  ]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 2, name: 'スキンケア' },
    { id: 3, name: '洗顔料' },
    { id: 4, name: 'ヘアケア' },
    { id: 5, name: 'ヘアトニック' },
    { id: 6, name: 'ボディウォッシュ' },
    { id: 7, name: '制汗剤' },
    { id: 8, name: 'カミソリ' },
    { id: 9, name: 'シェービング剤' },
    { id: 10, name: 'その他' }
  ]
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :text, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  has_many :comments

  belongs_to_active_hash :category

  with_options presence: true do
  validates :image
  validates :item_name
  validates :item_brand
  validates :item_maker
  validates :content
  validates :rate
  end

  validates :category_id, numericality: { other_than: 1, message:'Select' }
end

app/models/skintype.rb
class Skintype < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '脂性肌' },
    { id: 3, name: '乾燥肌' },
    { id: 4, name: '混合肌' },
    { id: 5, name: '普通肌' }
  ]
  end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :age
  belongs_to_active_hash :skintype
  has_many :reviews
  has_many :comments
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', nickname: 'テストユーザー', first_name: '五郎', last_name: '山田', first_name_kana: 'ゴロウ', last_name_kana: 'ヤマダ', age_id: '2', skintype_id: '2') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'Full-width characters' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'Full-width characters' }
    validates :first_name_kana, format: { with: /\A[ァ-ン]+\z/, message: 'Full-width katakana characters' }
    validates :last_name_kana, format: { with: /\A[ァ-ン]+\z/, message: 'Full-width katakana characters' }
  end
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

  validates :age_id, numericality: { other_than: 1, message:'Select' }
  validates :skintype_id, numericality: { other_than: 1, message:'Select' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :age_id, :skintype_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/reviews/#{comment.review.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :search_review, only: [:index, :search]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.includes(:user).order("created_at DESC")
    set_review_column
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  def search
    @results = @p.result.order("created_at DESC")
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:image, :item_name, :item_brand, :item_maker, :content, :rate, :category_id).merge(user_id: current_user.id)
  end

  def search_review
    @p = Review.ransack(params[:q])
  end

  def set_review_column
    @review_rate = Review.select("rate").distinct.order('rate DESC')
    @review_item_brand = Review.select("item_brand").distinct.order('item_brand ASC')
    @review_item_maker = Review.select("item_maker").distinct.order('item_brand DESC')
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @reviews = @user.reviews
    @age = @user.age.name
    @skintype = @user.skintype.name
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'users/show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'users/show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MensupCosme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6">
        <%= link_to image_tag("icon.jpg", class:"mens_up-icon",:size =>'70x70'), "/"  %>
        <a href="/">Men's up Cosme</a>
        </h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <div>
              <span><%= current_user.nickname %>
                <ul class="user_info">
                  <li>
                    <%= link_to 'マイページ', "/users/#{current_user.id}", class: "user-nickname" %>
                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
                  </li>
                </ul>
              </span>
            </div>
            <div>
              <%= link_to "投稿する", new_review_path, class: "post" %>
            </div>
          </div>
        <% else %>
          <div class="grid-6">
            <div class="gest_login">
              <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "post gest" %>
            </div>
            <div class="main_login">
              <%= link_to 'ログイン', user_session_path, class: "post" %>
              <%= link_to '新規登録', new_user_registration_path, class: "post" %>
            </div>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright Men's up Cosme 2020.
      </p>
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
      <div>
            <p class="form_exp">写真　※必須</p>
            <%= form.file_field :image, id:"item-image" %>
      </div>
      <div>
            <p class="form_exp">商品名　※必須</p>
            <%= form.text_field :item_name, placeholder: "商品名を入力してください" %>
      </div>
      <div>
            <p class="form_exp">ブランド名　※必須</p>
            <%= form.text_field :item_brand, placeholder: "ブランド名を入力してください" %>
      </div>
      <div>
            <p class="form_exp">メーカー名　※必須</p>
            <%= form.text_field :item_maker, placeholder: "メーカー名を入力してください" %>
      </div>
      <div>
            <p class="form_exp">カテゴリー　※必須</p>
            <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      </div>
      <br>
      <p class="form_exp">星評価　※必須</p>
      <div class="form" id="star">
            <%= form.label :rate ,"評価：", id: "e"%>
            <%= form.hidden_field :rate, id: :review_star %>
      </div>
      <br>
      <script>
            $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'review[rate]',
            half: true,
            });
      </script>
      <div>
            <p class="form_exp">レビュー　※必須</p>
            <%= form.text_area :content, placeholder: "レビューを入力してください", rows: "10" %>
      </div>
      <%= form.submit "SEND" %>

app/views/reviews/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @review, local: true) do |form| %>
      <h3>レビューを投稿する</h3>
      <%= render 'shared/error_messages', model: form.object %>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>

app/views/reviews/index.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="search_box">
    <div class="search_title">
      レビュー検索
    </div>
    <div class="search_form">
      <%= search_form_for @p, url: reviews_search_path do |f| %>
        <%= f.label :item_name_cont, '商品名' %>
        <div class="search_field">
          <%= f.search_field :item_name_cont %>
        </div>
        <%= f.label :rate_eq, '評価' %>
        <%= f.collection_select :rate_eq, @review_rate, :rate, :rate,  include_blank: '--' %>
        <%= f.label :item_brand_eq, 'ブランド名' %>
        <%= f.collection_select :item_brand_eq, @review_item_brand, :item_brand, :item_brand,  include_blank: '--' %>
        <%= f.label :item_maker_eq, 'メーカー名' %>
        <%= f.collection_select :item_maker_eq, @review_item_maker, :item_maker, :item_maker,  include_blank: '--' %>
        <%= f.label :category_id_eq, 'カテゴリー名' %>
        <%= f.collection_select :category_id_eq, Category.all, :id, :name,  include_blank: '--'%>
        <br>
        <div class="search_btn">
          <%= f.submit '検索' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="contents">
    <div class="contents_title">
      〜 最新のレビュー一覧 〜
    </div>
    <ul class="review_lists">
      <% @reviews.each do |review| %>
        <div class="review_list">
          <div class="more">
            <span><%= image_tag 'arrow_top.png' %></span>
              <ul class="more_list">
                <li>
                  <%= link_to '詳細', review_path(review.id), method: :get %>
                </li>
                  <% if user_signed_in? && current_user.id == review.user_id %>
                <li>
                  <%= link_to '編集', edit_review_path(review.id), method: :get %>
                </li>
                <li>
                  <%= link_to '削除', review_path(review.id), method: :delete %>
                </li>
                <% end %>
              </ul>
          </div>
          <div class="review">
            <div class="reviw_image">
              <%= image_tag review.image , class: 'review-image-image'%>
            </div>
            <div class="review_info">
              <div class="review_item_name">
                商品名：<%= review.item_name %>
              </div>
              <div class="review_brand">
                ブランド名：<%= review.item_brand %>
              </div>
              <div class="review_brand">
                メーカー名：<%= review.item_maker %>
              </div>
              <div class="review_item_category">
                カテゴリー：<%= review.category.name %>
              </div>
              <div class="review_item_rate">
                評価：<%= review.rate %>
              </div>
              <div class="review_item_rate" id="star-rate-<%= review.id %>"></div>
                  <script>
                  $('#star-rate-<%= review.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= review.rate %>,
                  });
                  </script>
              <span class="reviwe_content">レビュー：<%= review.content %></span>
            </div>
            <span class="name">
              <a href="/users/<%= review.user.id %>">
                <span>投稿者:</span><%= review.user.nickname %>
              </a>
            </span>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @review, url: reviews_path, method: :post, local: true) do |form| %>
      <h3>レビューを投稿する</h3>
      <%= render 'shared/error_messages', model: form.object %>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>

app/views/reviews/search.html.erb
<%= render "shared/second_header" %>
<div class="contents row">
  <div class="search_box">
    <div class="search_title">
      検索条件
    </div>
    <div class="search_query">
      <div>
        <% unless params[:q][:item_name_cont].empty?%>
          商品名： <%= params[:q][:item_name_cont] %>
        <% end %>
      </div>
      <div>
        <% unless params[:q][:rate_eq].empty?%>
          評価： <%= params[:q][:rate_eq] %>
        <% end %>
      </div>
      <div>
        <% unless params[:q][:item_brand_eq].empty?%>
          ブランド名： <%= params[:q][:item_brand_eq] %>
        <% end %>
      </div>
      <div>
        <% unless params[:q][:item_maker_eq].empty?%>
          メーカー名： <%= params[:q][:item_maker_eq] %>
        <% end %>
      </div>
      <div>
        <% unless params[:q][:category_id_eq].empty? %>
          カテゴリー： <%= Category.find(params[:q][:category_id_eq]).name %>
        <% end %>
      </div>
    </div>
    <div class="top-link">
      <%= link_to 'トップへ戻る', '/' %>
    </div>
  </div>
  <div class="contents_title">
    〜 レビュー一覧 〜
  </div>
  <ul class="review_lists">
    <% @results.each do |result| %>
      <div class="review_list">
        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
            <ul class="more_list">
              <li>
                <%= link_to '詳細', review_path(result.id), method: :get %>
              </li>
              <% if user_signed_in? && current_user.id == result.user_id %>
                <li>
                  <%= link_to '編集', edit_review_path(result.id), method: :get %>
                </li>
                <li>
                  <%= link_to '削除', review_path(result.id), method: :delete %>
                </li>
              <% end %>
            </ul>
        </div>
        <div class="review">
          <div class="reviw_image">
            <%= image_tag result.image.variant(resize: '120x180'), class: 'review-image-image' %>
          </div>
          <div class="review_info">
            <div class="review_item_name">
              商品名：<%= result.item_name %>
            </div>
            <div class="review_brand">
              ブランド名：<%= result.item_brand %>
            </div>
            <div class="review_brand">
              メーカー名：<%= result.item_maker %>
            </div>
            <div class="review_item_category">
              カテゴリー：<%= result.category.name %>
            </div>
            <div class="review_item_rate">
              評価：<%= result.rate %>
            </div>
            <div class="review_item_rate" id="star-rate-<%= result.id %>"></div>
                <script>
                $('#star-rate-<%= result.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= result.rate %>,
                });
                </script>
            <span class="reviwe_content">レビュー：<%= result.content %></span>
          </div>
          <span class="name">
            <a href="/users/<%= result.user.id %>">
              <span>投稿者:</span><%= result.user.nickname %>
            </a>
          </span>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/reviews/show.html.erb
<div class="contents row">
  <div class="review_list" >
    <% if user_signed_in? && current_user.id == @review.user_id %>
      <div class="show_more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="show_more_list">
          <li>
            <%= link_to '編集', edit_review_path(@review.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', review_path(@review.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <div class="review_show">
      <div class="reviw_show_image">
        <%= image_tag @review.image.variant(resize: '500x500') %>
      </div>
      <div class="review_show_info">
        <div class="review_show_item_name">
          商品名：<%= @review.item_name %>
        </div>
        <div class="review_show_brand">
          ブランド名：<%= @review.item_brand %>
        </div>
        <div class="review_show_brand">
          メーカー名：<%= @review.item_maker %>
        </div>
        <div class="review_show_item_category">
          カテゴリー：<%= @review.category.name %>
        </div>
        <div class="review_show_item_rate">
          評価：<%= @review.rate %>
        </div>
        <div class="review_show_item_rate" id="star-rate-<%= @review.id %>"></div>
            <script>
            $('#star-rate-<%= @review.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @review.rate %>,
            });
            </script>
        <span class="reviwe_show_content">レビュー：<%= @review.content %></span>
      </div>
    </div>
    <div class="name">
      <a href="/users/<%= @review.user.id %>">
        <span>投稿者:</span><%= @review.user.nickname %>
      </a>
    </div>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@review, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.reverse.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_second_header.html.erb
    <div class="top_contents" >
      <%= image_tag 'top_image4.png' %>
    </div>
    <div class="middle_contents">
      <h2>〜 メンズアップコスメとは 〜</h2>
      <p>身だしなみを整えたいけど「メンズコスメは種類が多くて何を使えばよいかわからない」</p>
      <p>そんなお悩みを解決するメンズのメンズによるメンズのためのコスメレビューサイト</p>
        <div class="middle_contents_info">
          <div class="middle_contents_block">
            <div class="middle_contents_icon"><%= image_tag 'reviwe_icon.png' %></div>
            <div class="middle_contents_text">リアルな口コミ</div>
            <div class="middle_contents_message">実際に使用した感想を口コミ投稿<br>もう商品購入に失敗しない</div>
          </div>
          <div class="middle_contents_block">
            <div class="middle_contents_icon"><%= image_tag 'search_icon.png' %></div>
            <div class="middle_contents_text">探しやすい</div>
            <div class="middle_contents_message">充実した検索機能<br>探したい商品が見つかる</div>
          </div>
          <div class="middle_contents_block">
            <div class="middle_contents_icon"><%= image_tag 'connection_icon.png' %></div>
            <div class="middle_contents_text">気軽に交流</div>
            <div class="middle_contents_message">レビューへのコメント機能<br>疑問点は気軽に質問</div>
          </div>
        </div>
    </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォローをやめる", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/show.html.erb
<%# プロフィール部分 %>
<div class="profile">
  <div class="profile_left">
    <div class="profile_image">
      <%= image_tag("mens_silhouette.jpg", class:"mens_silhouette",:size =>'150x150')%>
    </div>
    <% if user_signed_in? %>
      <div class="follow_btn">
        <% unless current_user?(@user) %>
          <div id="follow_form">
            <% if current_user.following?(@user) %>
              <%= render 'unfollow' %>
            <% else %>
              <%= render 'follow' %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <% @user ||= current_user %>
    <div class="stats">
      <%= link_to 'フォロー中：', following_user_path(@user) %>
        <strong id="following" class="stat">
          <%= @user.followings.count %>
        </strong>
      <br>
      <%= link_to 'フォロワー：', followers_user_path(@user) %>
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
    </div>
  </div>
  <div class="profile_info">
    <div>ユーザー名： <%= @nickname %></div>
    <div>年齢： <%= @age %></div>
    <div>肌タイプ： <%= @skintype %></div>
  </div>
</div>
<%# プロフィール部分 %>

<%# レビュー一覧部分 %>
<div class="contents row">
  <div class="contents_title">
    〜 <%= @nickname %>さんのレビュー一覧 〜
  </div>
  <ul class="review_lists">
    <% @reviews.reverse_each do |review| %>
      <div class="review_list">
        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
            <ul class="more_list">
              <li>
                <%= link_to '詳細', review_path(review.id), method: :get %>
              </li>
                <% if user_signed_in? && current_user.id == review.user_id %>
              <li>
                <%= link_to '編集', edit_review_path(review.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', review_path(review.id), method: :delete %>
              </li>
              <% end %>
            </ul>
        </div>
        <div class="review">
          <div class="reviw_image">
            <%= image_tag review.image.variant(resize: '120x180'), class: 'review_show_image' %>
          </div>
          <div class="review_info">
            <div class="review_item_name">
              商品名：<%= review.item_name %>
            </div>
            <div class="review_brand">
              ブランド名：<%= review.item_brand %>
            </div>
            <div class="review_brand">
              メーカー名：<%= review.item_maker %>
            </div>
            <div class="review_item_category">
              カテゴリー：<%= review.category.name %>
            </div>
            <div class="review_item_rate">
              評価：<%= review.rate %>
            </div>
            <div class="review_item_rate" id="star-rate-<%= review.id %>"></div>
                <script>
                $('#star-rate-<%= review.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
                });
                </script>
            <span class="reviwe_content">レビュー：<%= review.content %></span>
          </div>
          <span class="name">
            <a href="/users/<%= review.user.id %>">
              <span>投稿者:</span><%= review.user.nickname %>
            </a>
          </span>
        </div>
      </div>
    <% end %>
  </ul>
</div>
<%# レビュー一覧部分 %>

app/views/users/show_follow.html.erb
<div class="follow_top">
  〜 フォローしているユーザー 〜
</div>
<% @user.followings.each do |user| %>
  <div class="user_lists">
    <div class="user_list">
      <div class="user_list_nickname">  <%= user.nickname %> </div>
      <div class="user_list_userpage">  <%= link_to '詳細', user_path(user) %></div>
    </div>
  </div>
<% end %>

app/views/users/show_follower.html.erb
<div class="follow_top">
  〜 フォロされているユーザー 〜
</div>
<% @user.followers.each do |user| %>
  <div class="user_lists">
    <div class="user_list">
      <div class="user_list_nickname">  <%= user.nickname %> </div>
      <div class="user_list_userpage">  <%= link_to '詳細', user_path(user) %></div>
    </div>
  </div>
<% end %>